sudo: enabled
dist: trusty

services:
 - docker

before_install:
  - sudo add-apt-repository -y ppa:qpid/released
  - sudo apt-get -qq update
  - sudo apt-get -y install make python-qpid-proton

script:
 - make big-test
